export const urlPage = {
  DASHBOARD: '/dashboard',
  NOTIFICATION: '/notification',
  CONTACT: '/contact',
  CONTACT_ADD: '/contact/add',
  CONTACT_ADD_CATEGORY: '/contact/add-category',
  CONTACT_ME: '/contact/me',
  CONTACT_OTHER: '/contact/other',
  LOAN: '/loan',
  PRODUCT: '/product',
  PRODUCT_ADD: '/add-product',
  PRODUCT_ADD_CATEGORY: '/add-category',
  PRODUCT_BANK: '/product/bank',
  PRODUCT_BANK_ADD: '/product/bank/add',
  PRODUCT_DEVELOPER: '/product/developer',
  BANK: '/bank',
  CREDIT_SCORING: '/credit-scoring',
  CREDIT_SCORING_INDIVIDUAL: '/credit-scoring/individual',
  CREDIT_SCORING_COMPANY: '/credit-scoring/company',
  FAQ: '/faq',
  PIPELINE: '/pipeline',
  PIPELINE_DEV: '/pipeline-developer',
  MARKETING_TOOL: '/marketing-tool',
  WHATSAPP_REPORT: '/whatsapp-report',
};
