export const timelineNotif = [
  {
    time: '2 hrs',
    status: 'admin_branch has updated',
    details: 'Harry Handoko - Contact | MYCRM',
    isActive: true,
  },
  {
    time: '2 hrs',
    status: 'admin_branch has updated',
    details: 'Harry Handoko - Application | MYCRM',
    isActive: false,
  },
  {
    time: '4 hrs',
    status: 'admin_branch has updated',
    details: 'Harry Handoko - Application | MYCRM',
    isActive: true,
  },
  {
    time: '4 hrs',
    status: 'admin_branch has updated',
    details: 'Harry Handoko - Contact | MYCRM',
    isActive: false,
  },
  {
    time: '2 hrs',
    status: 'admin_branch has updated',
    details: 'Harry Handoko - Contact | MYCRM',
    isActive: true,
  },
  {
    time: '2 hrs',
    status: 'admin_branch has updated',
    details: 'Harry Handoko - Application | MYCRM',
    isActive: false,
  },
];

export const dataProductBank = [
  {
    id: 1,
    img: 'https://www.bankmandiri.co.id/image/layout_set_logo?img_id=31567&t=1731690239177',
    bank_name: 'Mandiri',
    rating: '3',
    reviews: '14',
    users: '220',
    product_name: 'Bunga Special Tengah Imlek 2023',
    product_type: 'Kredit kepemilikan Rakyat',
    year_fix_rate: 3.88,
    max_tenor: 12,
    loan_to_value: 1,
    guarantee: ['Ruko', 'Rukan', 'Rumah', 'Apartement'],
    target_market: ['Karyawan', 'Pengusaha', 'Milenial'],
    commision: 1,
    penalty_fee: 0,
    interest_rate: 3.6,
    fix_rate: 3.88,
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis nemo id incidunt fugiat. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis nemo id incidunt fugiat. ',
    appraisal: 1,
    floating: 1,
    url: 'null',
    promotial_date: [new Date('2024-02-01'), new Date('2024-02-10')],
    branch: [
      {
        id: 1,
        name: 'Jakarta Barat',
        rating: '4',
        address: 'Jl. Jakbar bla bla...',
        reviews: '1800',
      },
      {
        id: 2,
        name: 'Sudirman',
        rating: '5',
        address: 'Jl. Sudirman bla bla...',
        reviews: '2300',
      },
      {
        id: 3,
        name: 'Jakarta Utara',
        rating: '3',
        address: 'Jl. Jakut bla bla...',
        reviews: '450',
      },
      {
        id: 4,
        name: 'Bandung',
        rating: '4',
        address: 'Jl. Bandung bla bla...',
        reviews: '980',
      },
      {
        id: 5,
        name: 'Bogor',
        rating: '2',
        address: 'Jl. Bogor bla bla...',
        reviews: '300',
      },
    ],
  },
  {
    id: 2,
    img: 'https://www.panin.co.id/sites/default/files/static/img/logo/panin-default.svg',
    bank_name: 'Panin',
    rating: '2',
    reviews: '9',
    users: '220',
    product_name: 'Panin KPR & KPR XTRA',
    product_type: 'Kredit kepemilikan Pejabat',
    year_fix_rate: 9.9,
    max_tenor: 10,
    loan_to_value: 85,
    guarantee: 'Ruko, Rukan, Rumah, Apartement',
    target_market: 'Karyawan',
    commision: 1,
    penalty_fee: 0,
    interest_rate: 3.6,
    fix_rate: 3.88,
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis nemo id incidunt fugiat.',
    appraisal: 1,
    floating: 1,
    url: 'null',
    promotial_date: null,
    branch: [
      {
        id: 1,
        name: 'Jakarta Barat',
        rating: '4',
        address: 'Jl. Jakbar bla bla...',
        reviews: '1800',
      },
      {
        id: 2,
        name: 'Sudirman',
        rating: '5',
        address: 'Jl. Sudirman bla bla...',
        reviews: '2300',
      },
      {
        id: 3,
        name: 'Jakarta Utara',
        rating: '3',
        address: 'Jl. Jakut bla bla...',
        reviews: '450',
      },
    ],
  },
  {
    id: 3,
    img: 'https://mncbank.co.id/image/mnc_logo.png',
    bank_name: 'MNC',
    rating: '4',
    reviews: '10',
    users: '220',
    product_name: 'MNC KPR Secondary',
    product_type: 'Kredit kepemilikan Guru',
    year_fix_rate: 12,
    max_tenor: 1,
    loan_to_value: 50,
    guarantee: ['Rumah', 'Apartement'],
    target_market: ['Karyawan', 'Pengusaha', 'Milenial'],
    commision: 1,
    penalty_fee: 2,
    interest_rate: 3.6,
    fix_rate: 3.88,
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis nemo id incidunt fugiat.',
    appraisal: 1,
    floating: 1,
    url: 'null',
    promotial_date: null,
    branch: [
      {
        id: 1,
        name: 'Jakarta Barat',
        rating: '4',
        address: 'Jl. Jakbar bla bla...',
        reviews: '1800',
      },
      {
        id: 2,
        name: 'Sudirman',
        rating: '5',
        address: 'Jl. Sudirman bla bla...',
        reviews: '2300',
      },
    ],
  },
  {
    id: 4,
    img: 'https://logonoid.com/images/commonwealth-bank-logo.png',
    bank_name: 'Commonwealth',
    rating: '3',
    reviews: '10',
    users: '220',
    product_name: 'KPR Primary',
    product_type: 'Kredit kepemilikan Rakyat',
    year_fix_rate: null, // string kosong ("") diubah menjadi null
    max_tenor: null,
    loan_to_value: null,
    guarantee: ['Ruko', 'Rukan', 'Rumah', 'Apartement'],
    target_market: ['POLRI', 'TNI', 'Profesional'],
    commision: 2.4,
    penalty_fee: 0,
    interest_rate: 3.6,
    fix_rate: 3.88,
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis nemo id incidunt fugiat.',
    appraisal: 1,
    floating: 1,
    url: 'null',
    promotial_date: null,
    branch: [
      {
        id: 1,
        name: 'Bandung',
        rating: '4',
        address: 'Jl. Bandung bla bla...',
        reviews: '980',
      },
      {
        id: 2,
        name: 'Bogor',
        rating: '2',
        address: 'Jl. Bogor bla bla...',
        reviews: '300',
      },
    ],
  },
  {
    id: 5,
    img: 'https://logonoid.com/images/commonwealth-bank-logo.png',
    bank_name: 'Commonwealth',
    rating: '3',
    reviews: '9',
    users: '220',
    product_name: 'KPR Secondary',
    product_type: 'Kredit kepemilikan Rakyat',
    year_fix_rate: 2,
    max_tenor: null,
    loan_to_value: null,
    guarantee: ['Slip Gaji', 'Kendaraan Pribadi', 'Rumah', 'Apartement'],
    target_market: ['ASN', 'TNI', 'Karyawan'],
    commision: 2.4,
    penalty_fee: 0,
    interest_rate: 3.6,
    fix_rate: 3.88,
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis nemo id incidunt fugiat.',
    appraisal: 1,
    floating: 1,
    url: 'null',
    branch: [
      {
        id: 1,
        name: 'Jakarta Barat',
        rating: '4',
        address: 'Jl. Jakbar bla bla...',
        reviews: '1800',
      },
      {
        id: 2,
        name: 'Sudirman',
        rating: '5',
        address: 'Jl. Sudirman bla bla...',
        reviews: '2300',
      },
      {
        id: 3,
        name: 'Jakarta Utara',
        rating: '3',
        address: 'Jl. Jakut bla bla...',
        reviews: '450',
      },
      {
        id: 4,
        name: 'Bandung',
        rating: '4',
        address: 'Jl. Bandung bla bla...',
        reviews: '980',
      },
      {
        id: 5,
        name: 'Bogor',
        rating: '2',
        address: 'Jl. Bogor bla bla...',
        reviews: '300',
      },
    ],
  },
  {
    id: 6,
    img: 'https://www.uob.co.id/iwov-resources/assets/BrandAssets/UOB_Logo.png',
    bank_name: 'UOB',
    rating: '0',
    reviews: '0',
    users: '220',
    product_name: 'KPR Secondary',
    product_type: 'Kredit kepemilikan Pejabat',
    year_fix_rate: 3.99,
    max_tenor: null,
    loan_to_value: null,
    guarantee: ['Slip Gaji', 'Kendaraan Pribadi', 'Rumah', 'Apartement'],
    target_market: ['ASN', 'TNI', 'Karyawan'],
    commision: 1,
    penalty_fee: 0,
    interest_rate: 3.6,
    fix_rate: 3.88,
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis nemo id incidunt fugiat.',
    appraisal: 1,
    floating: 1,
    url: 'null',
    promotial_date: null,
    branch: [
      {
        id: 1,
        name: 'Jakarta Barat',
        rating: '4',
        address: 'Jl. Jakbar bla bla...',
        reviews: '1800',
      },
      {
        id: 2,
        name: 'Sudirman',
        rating: '5',
        address: 'Jl. Sudirman bla bla...',
        reviews: '2300',
      },
      {
        id: 3,
        name: 'Jakarta Utara',
        rating: '3',
        address: 'Jl. Jakut bla bla...',
        reviews: '450',
      },
      {
        id: 4,
        name: 'Bandung',
        rating: '4',
        address: 'Jl. Bandung bla bla...',
        reviews: '980',
      },
    ],
  },
  {
    id: 7,
    img: 'https://www.bankmandiri.co.id/image/layout_set_logo?img_id=31567&t=1731690239177',
    bank_name: 'Mandiri',
    rating: '4',
    reviews: '200',
    users: '2200',
    product_name: 'KPR Mandiri',
    product_type: 'Kredit kepemilikan Guru',
    year_fix_rate: 3.75,
    max_tenor: 20,
    loan_to_value: 85,
    guarantee: ['Slip Gaji', 'Kendaraan Pribadi', 'Rumah', 'Apartement'],
    target_market: ['ASN', 'TNI', 'Pengusaha'],
    commision: 1.2,
    penalty_fee: 1.5,
    interest_rate: 3.8,
    fix_rate: 3.75,
    description:
      'KPR Mandiri menawarkan suku bunga kompetitif untuk pembelian rumah pertama.',
    appraisal: 1.6,
    floating: 1.9,
    url: 'null',
    promotial_date: null,
    branch: [
      {
        id: 1,
        name: 'Jakarta Barat',
        rating: '4',
        address: 'Jl. Jakbar bla bla...',
        reviews: '1800',
      },
    ],
  },
  {
    id: 8,
    img: 'https://www.bni.co.id/Portals/1/BNI/Images/logo-bni-new.png',
    bank_name: 'BNI',
    rating: '4',
    reviews: '90',
    users: '1500',
    product_name: 'KPR BNI Fleksi',
    product_type: 'Kredit kepemilikan Rakyat',
    year_fix_rate: 5.0,
    max_tenor: 25,
    loan_to_value: 90,
    guarantee: ['Rukan', 'Ruko', 'Rumah', 'Apartement'],
    target_market: ['Pengusaha', 'Milenial', 'Karyawan'],
    commision: 1.4,
    penalty_fee: 2,
    interest_rate: 5.2,
    fix_rate: 5.0,
    description:
      'KPR dengan pilihan suku bunga tetap untuk jangka waktu panjang.',
    appraisal: 1.8,
    floating: 2.0,
    url: 'null',
    promotial_date: null,
    branch: [
      {
        id: 1,
        name: 'Sudirman',
        rating: '5',
        address: 'Jl. Sudirman bla bla...',
        reviews: '2300',
      },
      {
        id: 2,
        name: 'Jakarta Utara',
        rating: '3',
        address: 'Jl. Jakut bla bla...',
        reviews: '450',
      },
    ],
  },
  {
    id: 9,
    img: 'https://www.danamon.co.id/-/media/ICON-DCWCOID/LOGO-HEADER/v2/logo-danamon-new.jpg?h=65&iar=0&mh=65&w=260&hash=7956F6C1540D0E791F9382A68CF12C90',
    bank_name: 'Danamon',
    rating: '3',
    reviews: '70',
    users: '1000',
    product_name: 'KPR Danamon',
    product_type: 'Kredit kepemilikan Rakyat',
    year_fix_rate: 6.0,
    max_tenor: 20,
    loan_to_value: 85,
    guarantee: ['Rukan', 'Ruko', 'Rumah', 'Apartement'],
    target_market: ['Pengusaha', 'Milenial', 'Karyawan'],
    commision: 1.3,
    penalty_fee: 1,
    interest_rate: 6.0,
    fix_rate: 6.0,
    description:
      'KPR Danamon memberikan kemudahan dan bunga kompetitif untuk pemilikan rumah.',
    appraisal: 1.7,
    floating: 2.1,
    url: 'null',
    promotial_date: null,
    branch: [
      {
        id: 1,
        name: 'Jakarta Barat',
        rating: '4',
        address: 'Jl. Jakbar bla bla...',
        reviews: '1800',
      },
      {
        id: 2,
        name: 'Sudirman',
        rating: '5',
        address: 'Jl. Sudirman bla bla...',
        reviews: '2300',
      },
      {
        id: 3,
        name: 'Jakarta Utara',
        rating: '3',
        address: 'Jl. Jakut bla bla...',
        reviews: '450',
      },
      {
        id: 4,
        name: 'Bandung',
        rating: '4',
        address: 'Jl. Bandung bla bla...',
        reviews: '980',
      },
      {
        id: 5,
        name: 'Bogor',
        rating: '2',
        address: 'Jl. Bogor bla bla...',
        reviews: '300',
      },
    ],
  },
  {
    id: 10,
    img: 'https://www.bca.co.id/-/media/Feature/Header/Header-Logo/logo-bca.svg?v=1',
    bank_name: 'BCA',
    rating: '5',
    reviews: '110',
    users: '1400',
    product_name: 'KPR BCA Syariah',
    product_type: 'Kredit kepemilikan Pejabat',
    year_fix_rate: 4.0,
    max_tenor: 15,
    loan_to_value: 85,
    guarantee: ['Rukan', 'Ruko', 'Rumah', 'Apartement'],
    target_market: ['Pengusaha', 'Milenial', 'Karyawan'],
    commision: 1.2,
    penalty_fee: 0,
    interest_rate: 4.0,
    fix_rate: 4.0,
    description:
      'KPR BCA Syariah memberikan kemudahan untuk Anda yang menginginkan pembiayaan sesuai prinsip syariah.',
    appraisal: 2.0,
    floating: 1.8,
    url: 'null',
    promotial_date: null,
    branch: [
      {
        id: 1,
        name: 'Jakarta Utara',
        rating: '3',
        address: 'Jl. Jakut bla bla...',
        reviews: '450',
      },
      {
        id: 2,
        name: 'Bandung',
        rating: '4',
        address: 'Jl. Bandung bla bla...',
        reviews: '980',
      },
    ],
  },
  {
    id: 11,
    img: 'https://bri.co.id/o/bri-corporate-theme/images/bri-logo.png',
    bank_name: 'BRI',
    rating: '4',
    reviews: '130',
    users: '1600',
    product_name: 'KPR BRI Super Jumbo',
    product_type: 'Kredit kepemilikan Guru',
    year_fix_rate: 4.25,
    max_tenor: 25,
    loan_to_value: 80,
    guarantee: ['Rukan', 'Ruko', 'Rumah', 'Apartement'],
    target_market: ['Pengusaha', 'Milenial', 'Karyawan'],
    commision: 1.6,
    penalty_fee: 1.2,
    interest_rate: 4.25,
    fix_rate: 4.5,
    description:
      'Program KPR BRI Super Jumbo dengan bunga ringan dan tenor panjang untuk pembelian rumah besar.',
    appraisal: 1.9,
    floating: 2.0,
    url: 'null',
    promotial_date: null,
    branch: [
      {
        id: 1,
        name: 'Jakarta Barat',
        rating: '4',
        address: 'Jl. Jakbar bla bla...',
        reviews: '1800',
      },
      {
        id: 2,
        name: 'Sudirman',
        rating: '5',
        address: 'Jl. Sudirman bla bla...',
        reviews: '2300',
      },
      {
        id: 3,
        name: 'Jakarta Utara',
        rating: '3',
        address: 'Jl. Jakut bla bla...',
        reviews: '450',
      },
      {
        id: 4,
        name: 'Bandung',
        rating: '4',
        address: 'Jl. Bandung bla bla...',
        reviews: '980',
      },
      {
        id: 5,
        name: 'Bogor',
        rating: '2',
        address: 'Jl. Bogor bla bla...',
        reviews: '300',
      },
    ],
  },
  {
    id: 12,
    img: 'https://www.banksinarmas.com/id/public/image/logo.png',
    bank_name: 'Bank Sinarmas',
    rating: '4',
    reviews: '60',
    users: '900',
    product_name: 'KPR Sinarmas Plus',
    product_type: 'Kredit kepemilikan Guru',
    year_fix_rate: 5.5,
    max_tenor: 20,
    loan_to_value: 85,
    guarantee: ['Rukan', 'Ruko', 'Rumah', 'Apartement'],
    target_market: ['Pengusaha', 'Milenial', 'Karyawan'],
    commision: 1.0,
    penalty_fee: 1,
    interest_rate: 5.6,
    fix_rate: 5.5,
    description:
      'KPR Sinarmas Plus menawarkan kemudahan dengan bunga tetap selama tenor yang lebih lama.',
    appraisal: 1.6,
    floating: 1.8,
    url: 'null',
    promotial_date: null,
    branch: [
      {
        id: 1,
        name: 'Jakarta Barat',
        rating: '4',
        address: 'Jl. Jakbar bla bla...',
        reviews: '1800',
      },
      {
        id: 2,
        name: 'Sudirman',
        rating: '5',
        address: 'Jl. Sudirman bla bla...',
        reviews: '2300',
      },
    ],
  },
  {
    id: 13,
    img: 'https://www.bni.co.id/Portals/1/BNI/Images/logo-bni-new.png',
    bank_name: 'BNI',
    rating: '4',
    reviews: '90',
    users: '1100',
    product_name: 'KPR BNI Prioritas',
    product_type: 'Kredit kepemilikan Pejabat',
    year_fix_rate: 4.75,
    max_tenor: 25,
    loan_to_value: 85,
    guarantee: ['Rukan', 'Ruko', 'Rumah', 'Apartement'],
    target_market: ['Pengusaha', 'Milenial', 'Karyawan'],
    commision: 1.3,
    penalty_fee: 1.2,
    interest_rate: 4.75,
    fix_rate: 4.8,
    description:
      'KPR Prioritas BNI untuk pemilikan rumah dengan fasilitas lebih unggul.',
    appraisal: 2.0,
    floating: 1.9,
    url: 'null',
    promotial_date: null,
    branch: [
      {
        id: 1,
        name: 'Jakarta Barat',
        rating: '4',
        address: 'Jl. Jakbar bla bla...',
        reviews: '1800',
      },
      {
        id: 2,
        name: 'Bogor',
        rating: '2',
        address: 'Jl. Bogor bla bla...',
        reviews: '300',
      },
    ],
  },
  {
    id: 14,
    img: 'https://www.bni.co.id/Portals/1/BNI/Images/logo-bni-new.png',
    bank_name: 'BNI',
    rating: '5',
    reviews: '160',
    users: '2000',
    product_name: 'KPR Plus BNI',
    product_type: 'Kredit kepemilikan Pejabat',
    year_fix_rate: 4.2,
    max_tenor: 30,
    loan_to_value: 80,
    guarantee: ['Slip Gaji', 'Kendaraan Pribadi', 'Rumah', 'Apartement'],
    target_market: ['ASN', 'TNI', 'Pengusaha'],
    commision: 1.5,
    penalty_fee: 1,
    interest_rate: 4.2,
    fix_rate: 4.3,
    description:
      'KPR Plus BNI menawarkan kemudahan untuk membeli rumah impian dengan bunga yang lebih ringan.',
    appraisal: 1.8,
    floating: 2.0,
    url: 'null',
    promotial_date: null,
    branch: [
      {
        id: 1,
        name: 'Jakarta Barat',
        rating: '4',
        address: 'Jl. Jakbar bla bla...',
        reviews: '1800',
      },
      {
        id: 2,
        name: 'Sudirman',
        rating: '5',
        address: 'Jl. Sudirman bla bla...',
        reviews: '2300',
      },
      {
        id: 3,
        name: 'Jakarta Utara',
        rating: '3',
        address: 'Jl. Jakut bla bla...',
        reviews: '450',
      },
      {
        id: 4,
        name: 'Bandung',
        rating: '4',
        address: 'Jl. Bandung bla bla...',
        reviews: '980',
      },
      {
        id: 5,
        name: 'Bogor',
        rating: '2',
        address: 'Jl. Bogor bla bla...',
        reviews: '300',
      },
    ],
  },
  {
    id: 15,
    img: 'https://www.danamon.co.id/-/media/ICON-DCWCOID/LOGO-HEADER/v2/logo-danamon-new.jpg?h=65&iar=0&mh=65&w=260&hash=7956F6C1540D0E791F9382A68CF12C90',
    bank_name: 'Danamon',
    rating: '3',
    reviews: '45',
    users: '600',
    product_name: 'KPR Danamon Syariah',
    product_type: 'Kredit kepemilikan Rakyat',
    year_fix_rate: 5.0,
    max_tenor: 20,
    loan_to_value: 85,
    guarantee: ['Slip Gaji', 'Kendaraan Pribadi', 'Rumah', 'Apartement'],
    target_market: ['ASN', 'TNI', 'Pengusaha'],
    commision: 1.3,
    penalty_fee: 0,
    interest_rate: 5.1,
    fix_rate: 5.0,
    description:
      'KPR Syariah Danamon menawarkan solusi pembiayaan rumah sesuai prinsip syariah.',
    appraisal: 1.7,
    floating: 1.9,
    url: 'null',
    promotial_date: null,
    branch: [],
  },
];

export const dataProdctDeveloper = [
  {
    id: 1,
    name_product: 'Kingland Avenue',
    name_dev: 'Kingland Avenue',
    price: 0,
    type_product: 'Property Apartment',
    total: '224',
    type_property: 'Kredit Pemilikan Apartement (KPA)',
    unit: 0,
    address: '-',
  },
  {
    id: 2,
    name_product: 'Eastern Green',
    price: 0,
    type_product: 'Property Apartment',
    total: '456',
    name_dev: 'LRT City Bekasi',
    type_property: 'Kredit Pemilikan Apartement (KPA)',
    unit: 10,
    address: '-',
  },
  {
    id: 3,
    name_product: 'Tamansari',
    price: 0,
    type_product: 'Property Apartment',
    total: '224',
    name_dev: 'PT. Wijaya Karya',
    type_property: 'Kredit Pemilikan Apartement (KPA)',
    unit: 20,
    address: '-',
  },
  {
    id: 4,
    name_product: 'Green Avenue',
    price: 0,
    type_product: 'Property Apartment',
    total: '224',
    name_dev: 'PT. ABC',
    type_property: 'Kredit Pemilikan Apartement (KPA)',
    unit: 0,
    address: '-',
  },
  {
    id: 5,
    name_product: 'Kingland Avenue',
    price: 0,
    type_product: 'Property Apartment',
    total: '224',
    name_dev: 'PT Hongkong KingLand',
    type_property: 'Kredit Pemilikan Apartement (KPA)',
    unit: 0,
    address: '-',
  },
  {
    id: 6,
    name_product: 'Kingland Avenue',
    price: 0,
    type_product: 'Property Apartment',
    total: '224',
    name_dev: 'PT Hongkong KingLand',
    type_property: 'Kredit Pemilikan Apartement (KPA)',
    unit: 0,
    address: '-',
  },
  {
    id: 7,
    name_product: 'Kingland Avenue',
    price: 0,
    type_product: 'Property Apartment',
    total: '224',
    name_dev: 'PT Hongkong KingLand',
    type_property: 'Kredit Pemilikan Apartement (KPA)',
    unit: 0,
    address: '-',
  },
  {
    id: 8,
    name_product: 'Tamansari',
    price: 0,
    type_product: 'Property Apartment',
    total: '224',
    name_dev: 'PT. Wijaya Karya',
    type_property: 'Kredit Pemilikan Apartement (KPA)',
    unit: 0,
    address: '-',
  },
];

export const dataContact = [
  {
    id: 1,
    name: 'Ravi Achmad',
    gender: 'Laki-laki',
    position: 'Karyawan',
    email: 'ahmad@gmail.com',
    phone: '90000000',
    type: 'my',
    contact_type: 'perusahaan',
    birth_date: new Date(2025, 3, 2),
    nik: '0091828120',
    adviser: 'Junaidi',
    created_at: 'February 22, 2025',
    employment_type: 'Wiraswasta',
    company: 'PT ABC',
    contact_category: 'Hot leads',
  },
  {
    id: 2,
    name: 'Maria Sari',
    gender: 'Perempuan',
    position: 'Manager',
    email: 'maria@gmail.com',
    phone: '90000001',
    type: 'my',
    contact_type: 'perorangan',
    birth_date: new Date(2025, 3, 2),
    nik: '99988292',
    adviser: 'Junaidi',
    created_at: 'June 19, 2034',
    employment_type: 'Profesional',
    company: 'PT KOCAK GEMING',
    contact_category: 'Warn leads',
  },
  {
    id: 3,
    name: 'John Doe',
    gender: 'Laki-laki',
    position: 'Supervisor',
    email: 'johndoe@gmail.com',
    phone: '90000002',
    type: 'my',
    contact_type: 'perusahaan',
    birth_date: new Date(2025, 0, 2),
    nik: '0091828120',
    adviser: 'Junaidi',
    created_at: 'December 12, 2019',
    employment_type: 'Wiraswasta',
    company: 'PT KOCAK GEMING',
    contact_category: 'Dev partner',
  },
  {
    id: 4,
    name: 'Aisyah Putri',
    gender: 'Perempuan',
    position: 'Staff',
    email: 'aisyah@gmail.com',
    phone: '90000003',
    type: 'my',
    contact_type: 'perorangan',
    birth_date: new Date(2025, 5, 10),
    nik: '8881234567',
    adviser: 'Rahmat',
    created_at: 'December 14, 2019',
    employment_type: 'Profesional',
    company: 'PT KOCAK GEMING',
    contact_category: 'Warn leads',
  },
  {
    id: 5,
    name: 'Budi Santoso',
    gender: 'Laki-laki',
    position: 'Karyawan',
    email: 'budi@gmail.com',
    phone: '90000004',
    type: 'my',
    contact_type: 'perusahaan',
    birth_date: new Date(2025, 7, 21),
    nik: '7776543210',
    adviser: 'Siti',
    created_at: 'June 19, 2034',
    employment_type: 'Profesional',
    company: 'PT KOCAK GEMING',
    contact_category: 'Cold leads',
  },
  {
    id: 6,
    name: 'Tina Rachmawati',
    gender: 'Perempuan',
    position: 'Asisten Manager',
    email: 'tina@gmail.com',
    phone: '90000005',
    type: 'my',
    contact_type: 'perorangan',
    birth_date: new Date(2025, 2, 15),
    nik: '6669876543',
    adviser: 'Amin',
    created_at: 'June 19, 2034',
    employment_type: 'Profesional',
    company: 'PT KOCAK GEMING',
    contact_category: 'Warn leads',
  },
  {
    id: 7,
    name: 'Ali Abdullah',
    gender: 'Laki-laki',
    position: 'Security',
    email: 'ali@gmail.com',
    phone: '90000006',
    type: 'my',
    contact_type: 'perusahaan',
    birth_date: new Date(2025, 10, 30),
    nik: '5553456789',
    adviser: 'Farhan',
    created_at: 'December 17, 2009',
    employment_type: 'Profesional',
    company: 'PT KOCAK GEMING',
    contact_category: 'Warn leads',
  },
  {
    id: 8,
    name: 'Dewi Lestari',
    gender: 'Perempuan',
    position: 'Admin',
    email: 'dewi@gmail.com',
    phone: '90000007',
    type: 'my',
    contact_type: 'perorangan',
    birth_date: new Date(2025, 1, 5),
    nik: '4449876543',
    adviser: 'Lukman',
    created_at: 'December 12, 2019',
    employment_type: 'Profesional',
    company: 'PT KOCAK GEMING',
    contact_category: 'Warn leads',
  },
  {
    id: 9,
    name: 'Riko Pratama',
    gender: 'Laki-laki',
    position: 'Marketing',
    email: 'riko@gmail.com',
    phone: '90000008',
    type: 'other',
    contact_type: 'perusahaan',
    birth_date: new Date(2025, 6, 12),
    nik: '3338765432',
    adviser: 'Nina',
    created_at: 'June 19, 2034',
    employment_type: 'Profesional',
    company: 'PT KOCAK GEMING',
    contact_category: 'Cold leads',
  },
  {
    id: 10,
    name: 'Siti Nurhaliza',
    gender: 'Perempuan',
    position: 'Staff HRD',
    email: 'siti@gmail.com',
    phone: '90000009',
    type: 'other',
    contact_type: 'perorangan',
    birth_date: new Date(2025, 4, 25),
    nik: '2227654321',
    adviser: 'Joko',
    created_at: 'June 19, 2034',
    employment_type: 'Profesional',
    company: 'PT KOCAK GEMING',
    contact_category: 'Warn leads',
  },
  {
    id: 11,
    name: 'Eko Wibowo',
    gender: 'Laki-laki',
    position: 'Accounting',
    email: 'eko@gmail.com',
    phone: '90000010',
    type: 'other',
    contact_type: 'perusahaan',
    birth_date: new Date(2025, 8, 8),
    nik: '1116543210',
    adviser: 'Dewi',
    created_at: 'June 19, 2034',
    employment_type: 'Profesional',
    company: 'PT KOCAK GEMING',
    contact_category: 'Dev partner',
  },
  {
    id: 12,
    name: 'Lina Yuliana',
    gender: 'Perempuan',
    position: 'Designer',
    email: 'lina@gmail.com',
    phone: '90000011',
    type: 'other',
    contact_type: 'perorangan',
    birth_date: new Date(2025, 11, 3),
    nik: '0005432109',
    adviser: 'Andi',
    created_at: 'May 19, 2034',
    employment_type: 'Profesional',
    company: 'PT KOCAK GEMING',
    contact_category: 'Warn leads',
  },
];

export const dataApplication = [
  {
    id: 1,
    userId: 2,
    loan_amount: 'Rp.200.000.000,00',
    loan_step: 'Belum diproses',
    tenor: '10 Tahun',
  },
  {
    id: 2,
    userId: 2,
    loan_amount: 'Rp.500.000.000,00',
    loan_step: 'Dikirim ke Bank',
    tenor: '13 Tahun',
  },
  {
    id: 2,
    userId: 7,
    loan_amount: 'Rp.70.000.000,00',
    loan_step: 'Dikirim ke Bank',
    tenor: '3 Tahun',
  },
  {
    id: 3,
    userId: 9,
    loan_amount: 'Rp.800.000.000,00',
    loan_step: 'Dikirim ke Bank',
    tenor: '10 Tahun',
  },
  {
    id: 4,
    userId: 5,
    loan_amount: 'Rp.400.000.000,00',
    loan_step: 'Belum diproses',
    tenor: '10 Tahun',
  },
  {
    id: 5,
    userId: 1,
    loan_amount: 'Rp.1.000.000.000,00',
    loan_step: 'Belum diproses',
    tenor: '10 Tahun',
  },
  {
    id: 6,
    userId: 12,
    loan_amount: 'Rp.2.000.000.000,00',
    loan_step: 'Belum diproses',
    tenor: '10 Tahun',
  },
];

export const dataBankOfficer = {
  bank: 'Mandiri',
  product: 'Kredit Kepemilikan Rumah Secondary (KPR Secondary)',
  region: 'Tidak Ada',
  bank_officer: 'Tidak Ada',
};

export const dataCreditScoring = [
  {
    name: 'Budi',
    ktpNpwp: '7656745644453',
    type: 'Individual',
    purpose: 'ProvidingFacilities',
    tanggal: '2022-02-24',
    status: 'Not Found',
  },
  {
    name: 'Suhandi',
    ktpNpwp: '7656745644453',
    type: 'Individual',
    purpose: 'ProvidingFacilities',
    tanggal: '2022-02-24',
    status: 'Not Found',
  },
  {
    name: 'Sukanti',
    ktpNpwp: '7656745644453',
    type: 'Individual',
    purpose: 'ProvidingFacilities',
    tanggal: '2022-02-24',
    status: 'Not Found',
  },
  {
    name: 'Sujangi',
    ktpNpwp: '7656745644453',
    type: 'Individual',
    purpose: 'ProvidingFacilities',
    tanggal: '2022-02-24',
    status: 'Not Found',
  },
  {
    name: 'Soekanto',
    ktpNpwp: '7656745644453',
    type: 'Individual',
    purpose: 'ProvidingFacilities',
    tanggal: '2022-02-24',
    status: 'Not Found',
  },
  {
    name: 'Sumardi',
    ktpNpwp: '7656745644453',
    type: 'Individual',
    purpose: 'ProvidingFacilities',
    tanggal: '2022-02-24',
    status: 'Not Found',
  },
  {
    name: 'Solihin',
    ktpNpwp: '7656745644453',
    type: 'Individual',
    purpose: 'ProvidingFacilities',
    tanggal: '2022-02-24',
    status: 'Not Found',
  },
  {
    name: 'Sodikin',
    ktpNpwp: '7656745644453',
    type: 'Individual',
    purpose: 'ProvidingFacilities',
    tanggal: '2022-02-24',
    status: 'Not Found',
  },
  {
    name: 'Sokamti',
    ktpNpwp: '7656745644453',
    type: 'Individual',
    purpose: 'ProvidingFacilities',
    tanggal: '2022-02-24',
    status: 'Not Found',
  },
  {
    name: 'Solihudin',
    ktpNpwp: '7656745644453',
    type: 'Individual',
    purpose: 'ProvidingFacilities',
    tanggal: '2022-02-24',
    status: 'Not Found',
  },
  {
    name: 'Samandi',
    ktpNpwp: '7656745644453',
    type: 'Individual',
    purpose: 'ProvidingFacilities',
    tanggal: '2022-02-24',
    status: 'Not Found',
  },
];

export const dataFaqs = [
  {
    id: 1,
    title: "FAQ's KPR Primary",
    details: [
      {
        id: 1,
        title: 'Apa itu KPR Primary?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 2,
        title: 'Apa keuntungan dari KPR Primary?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 3,
        title: 'Apa saja Dokumen Penunjang yang dibutuhkan dalam KPR Primary?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 4,
        title: 'Bagaimana cara mengajukan KPR Primary di Loan Market?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
    ],
  },
  {
    id: 2,
    title: "FAQ's Refinancing BPKB dan mesin/alat berat",
    details: [
      {
        id: 1,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 2,
        title: 'consectetur adipisicing elit.?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 3,
        title: 'Lorem ipsum',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
    ],
  },
  {
    id: 3,
    title: "FAQ's Take Over dan Bridging Loan",
    details: [
      {
        id: 1,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 2,
        title: 'consectetur adipisicing elit.?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
    ],
  },
  {
    id: 4,
    title: "FAQ's KPR Multiguna/KPR Secondary",
    details: [
      {
        id: 1,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 2,
        title: 'consectetur adipisicing elit.?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 3,
        title: 'Lorem ipsum',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 4,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
    ],
  },
  {
    id: 5,
    title: "FAQ's Form Renovasi",
    details: [
      {
        id: 1,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 2,
        title: 'consectetur adipisicing elit.?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
    ],
  },
  {
    id: 6,
    title: "FAQ's Form Kredit Modal Usaha dan Investasi/Rekening Koran",
    details: [
      {
        id: 1,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 2,
        title: 'consectetur adipisicing elit.?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 3,
        title: 'Lorem ipsum',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
    ],
  },
  {
    id: 7,
    title: "FAQ's Form Kredit Ivestasi",
    details: [
      {
        id: 1,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 2,
        title: 'consectetur adipisicing elit.?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 3,
        title: 'Lorem ipsum',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 4,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 5,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
    ],
  },
  {
    id: 8,
    title: "FAQ's Form Deposito",
    details: [
      {
        id: 1,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 2,
        title: 'consectetur adipisicing elit.?',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
      {
        id: 3,
        title: 'Lorem ipsum',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
    ],
  },
  {
    id: 9,
    title: "FAQ's Refinancing Kendaraan Bermotor",
    details: [
      {
        id: 1,
        title: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
        desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, corrupti perferendis rem harum provident dolores. Est, corporis eius! Explicabo, nam consequuntur esse nemo possimus porro sint quos suscipit eius earum?',
      },
    ],
  },
];
