export const timelineNotif = [
  {
    time: '2 hrs',
    status: 'admin_branch has updated',
    details: 'Harry Handoko - Contact | MYCRM',
    isActive: true,
  },
  {
    time: '2 hrs',
    status: 'admin_branch has updated',
    details: 'Harry Handoko - Application | MYCRM',
    isActive: false,
  },
  {
    time: '4 hrs',
    status: 'admin_branch has updated',
    details: 'Harry Handoko - Application | MYCRM',
    isActive: true,
  },
  {
    time: '4 hrs',
    status: 'admin_branch has updated',
    details: 'Harry Handoko - Contact | MYCRM',
    isActive: false,
  },
];

export const dataProductBank = [
  {
    id: 1,
    img: 'https://www.bankmandiri.co.id/image/layout_set_logo?img_id=31567&t=1731690239177',
    bank_name: 'Mandiri',
    rating: '3',
    reviews: '14',
    users: '220',
    product_name: 'Bunga Special Tengah Imlek 2023',
    product_type: 'Kredit kepemilikan Rakyat',
    year_fix_rate: '3.88',
    max_tenor: '12',
    loan_to_value: '1',
    guarantee: 'Ruko, Rukan, Rumah, Apartement',
    target_market: 'Karyawan, Pengusaha',
    commision: '1',
    penalty_fee: '0',
    interest_rate: '3.6',
    fix_rate: '3.88',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis nemo id incidunt fugiat.',
    appraisal: '1',
    floating: '1',
    url: 'null',
  },
  {
    id: 2,
    img: 'https://www.panin.co.id/sites/default/files/static/img/logo/panin-default.svg',
    bank_name: 'Panin',
    rating: '2',
    reviews: '9',
    users: '220',
    product_name: 'Panin KPR & KPR XTRA',
    product_type: 'Kredit kepemilikan Pejabat',
    year_fix_rate: '9.90',
    max_tenor: '10',
    loan_to_value: '85',
    guarantee: 'Ruko, Rukan, Rumah, Apartement',
    target_market: 'Karyawan',
    commision: '1',
    penalty_fee: '0',
    interest_rate: '3.6',
    fix_rate: '3.88',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis nemo id incidunt fugiat.',
    appraisal: '1',
    floating: '1',
    url: 'null',
  },
  {
    id: 3,
    img: 'https://mncbank.co.id/image/mnc_logo.png',
    bank_name: 'MNC',
    rating: '4',
    reviews: '10',
    users: '220',
    product_name: 'MNC KPR Secondary',
    product_type: 'Kredit kepemilikan Guru',
    year_fix_rate: '12',
    max_tenor: '1',
    loan_to_value: '50',
    guarantee: 'Rumah, Apartement',
    target_market: 'Karyawan',
    commision: '1',
    penalty_fee: '0',
    interest_rate: '3.6',
    fix_rate: '3.88',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis nemo id incidunt fugiat.',
    appraisal: '1',
    floating: '1',
    url: 'null',
  },
  {
    id: 4,
    img: 'https://logonoid.com/images/commonwealth-bank-logo.png',
    bank_name: 'Commonwealth',
    rating: '3',
    reviews: '10',
    users: '220',
    product_name: 'KPR Primary',
    product_type: 'Kredit kepemilikan Rakyat',
    year_fix_rate: '',
    max_tenor: null,
    loan_to_value: null,
    guarantee: 'Rumah, Apartement, Ruko, Rukan',
    target_market: 'Karyawan, Pengusaha, Profesional',
    commision: '2.4',
    penalty_fee: '0',
    interest_rate: '3.6',
    fix_rate: '3.88',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis nemo id incidunt fugiat.',
    appraisal: '1',
    floating: '1',
    url: 'null',
  },
  {
    id: 5,
    img: 'https://logonoid.com/images/commonwealth-bank-logo.png',
    bank_name: 'Commonwealth',
    rating: '3',
    reviews: '9',
    users: '220',
    product_name: 'KPR Secondary',
    product_type: 'Kredit kepemilikan Rakyat',
    year_fix_rate: '2',
    max_tenor: null,
    loan_to_value: null,
    guarantee: 'Rumah, Apartement, Ruko, Rukan',
    target_market: 'Karyawan, Pengusaha, Profesional',
    commision: '2.4',
    penalty_fee: '0',
    interest_rate: '3.6',
    fix_rate: '3.88',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis nemo id incidunt fugiat.',
    appraisal: '1',
    floating: '1',
    url: 'null',
  },
  {
    id: 6,
    img: 'https://www.uob.co.id/iwov-resources/assets/BrandAssets/UOB_Logo.png',
    bank_name: 'UOB',
    rating: '0',
    reviews: '0',
    users: '220',
    product_name: 'KPR Secondary',
    product_type: 'Kredit kepemilikan Pejabat',
    year_fix_rate: '3.99',
    max_tenor: null,
    loan_to_value: null,
    guarantee: 'Rumah, Apartement, Ruko, Rukan',
    target_market: 'Karyawan, Pengusaha, Profesional',
    commision: '1',
    penalty_fee: '0',
    interest_rate: '3.6',
    fix_rate: '3.88',
    description:
      'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis nemo id incidunt fugiat.',
    appraisal: '1',
    floating: '1',
    url: 'null',
  },
  {
    id: 7,
    img: 'https://www.bankmandiri.co.id/image/layout_set_logo?img_id=31567&t=1731690239177',
    bank_name: 'Mandiri',
    rating: '4',
    reviews: '200',
    users: '2200',
    product_name: 'KPR Mandiri',
    product_type: 'Kredit kepemilikan Guru',
    year_fix_rate: '3.75',
    max_tenor: '20',
    loan_to_value: '85',
    guarantee: 'Rumah, Apartemen',
    target_market: 'Karyawan, Pengusaha',
    commision: '1.2',
    penalty_fee: '1.5',
    interest_rate: '3.8',
    fix_rate: '3.75',
    description:
      'KPR Mandiri menawarkan suku bunga kompetitif untuk pembelian rumah pertama.',
    appraisal: '1.6',
    floating: '1.9',
    url: 'null',
  },
  {
    id: 8,
    img: 'https://www.bni.co.id/Portals/1/BNI/Images/logo-bni-new.png',
    bank_name: 'BNI',
    rating: '4',
    reviews: '90',
    users: '1500',
    product_name: 'KPR BNI Fleksi',
    product_type: 'Kredit kepemilikan Rakyat',
    year_fix_rate: '5.0',
    max_tenor: '25',
    loan_to_value: '90',
    guarantee: 'Rumah, Apartemen',
    target_market: 'Karyawan, Profesional',
    commision: '1.4',
    penalty_fee: '2',
    interest_rate: '5.2',
    fix_rate: '5.0',
    description:
      'KPR dengan pilihan suku bunga tetap untuk jangka waktu panjang.',
    appraisal: '1.8',
    floating: '2.0',
    url: 'null',
  },
  {
    id: 9,
    img: 'https://www.danamon.co.id/-/media/ICON-DCWCOID/LOGO-HEADER/v2/logo-danamon-new.jpg?h=65&iar=0&mh=65&w=260&hash=7956F6C1540D0E791F9382A68CF12C90',
    bank_name: 'Danamon',
    rating: '3',
    reviews: '70',
    users: '1000',
    product_name: 'KPR Danamon',
    product_type: 'Kredit kepemilikan Rakyat',
    year_fix_rate: '6.0',
    max_tenor: '20',
    loan_to_value: '85',
    guarantee: 'Rumah, Apartemen',
    target_market: 'Karyawan, Pengusaha',
    commision: '1.3',
    penalty_fee: '1',
    interest_rate: '6.0',
    fix_rate: '6.0',
    description:
      'KPR Danamon memberikan kemudahan dan bunga kompetitif untuk pemilikan rumah.',
    appraisal: '1.7',
    floating: '2.1',
    url: 'null',
  },
  {
    id: 10,
    img: 'https://www.bca.co.id/-/media/Feature/Header/Header-Logo/logo-bca.svg?v=1',
    bank_name: 'BCA',
    rating: '5',
    reviews: '110',
    users: '1400',
    product_name: 'KPR BCA Syariah',
    product_type: 'Kredit kepemilikan Pejabat',
    year_fix_rate: '4.0',
    max_tenor: '15',
    loan_to_value: '85',
    guarantee: 'Rumah, Apartemen',
    target_market: 'Karyawan, Profesional, Pengusaha',
    commision: '1.2',
    penalty_fee: '0',
    interest_rate: '4.0',
    fix_rate: '4.0',
    description:
      'KPR BCA Syariah memberikan kemudahan untuk Anda yang menginginkan pembiayaan sesuai prinsip syariah.',
    appraisal: '2.0',
    floating: '1.8',
    url: 'null',
  },
  {
    id: 11,
    img: 'https://bri.co.id/o/bri-corporate-theme/images/bri-logo.png',
    bank_name: 'BRI',
    rating: '4',
    reviews: '130',
    users: '1600',
    product_name: 'KPR BRI Super Jumbo',
    product_type: 'Kredit kepemilikan Guru',
    year_fix_rate: '4.25',
    max_tenor: '25',
    loan_to_value: '80',
    guarantee: 'Rumah, Villa',
    target_market: 'Karyawan, Pengusaha',
    commision: '1.6',
    penalty_fee: '1.2',
    interest_rate: '4.25',
    fix_rate: '4.5',
    description:
      'Program KPR BRI Super Jumbo dengan bunga ringan dan tenor panjang untuk pembelian rumah besar.',
    appraisal: '1.9',
    floating: '2.0',
    url: 'null',
  },
  {
    id: 12,
    img: 'https://www.banksinarmas.com/id/public/image/logo.png',
    bank_name: 'Bank Sinarmas',
    rating: '4',
    reviews: '60',
    users: '900',
    product_name: 'KPR Sinarmas Plus',
    product_type: 'Kredit kepemilikan Guru',
    year_fix_rate: '5.5',
    max_tenor: '20',
    loan_to_value: '85',
    guarantee: 'Rumah, Apartemen',
    target_market: 'Karyawan, Pengusaha',
    commision: '1.0',
    penalty_fee: '1',
    interest_rate: '5.6',
    fix_rate: '5.5',
    description:
      'KPR Sinarmas Plus menawarkan kemudahan dengan bunga tetap selama tenor yang lebih lama.',
    appraisal: '1.6',
    floating: '1.8',
    url: 'null',
  },
  {
    id: 13,
    img: 'https://www.bni.co.id/Portals/1/BNI/Images/logo-bni-new.png',
    bank_name: 'BNI',
    rating: '4',
    reviews: '90',
    users: '1100',
    product_name: 'KPR BNI Prioritas',
    product_type: 'Kredit kepemilikan Pejabat',
    year_fix_rate: '4.75',
    max_tenor: '25',
    loan_to_value: '85',
    guarantee: 'Rumah, Apartemen',
    target_market: 'Karyawan, Profesional',
    commision: '1.3',
    penalty_fee: '1.2',
    interest_rate: '4.75',
    fix_rate: '4.8',
    description:
      'KPR Prioritas BNI untuk pemilikan rumah dengan fasilitas lebih unggul.',
    appraisal: '2.0',
    floating: '1.9',
    url: 'null',
  },
  {
    id: 14,
    img: 'https://www.bni.co.id/Portals/1/BNI/Images/logo-bni-new.png',
    bank_name: 'BNI',
    rating: '5',
    reviews: '160',
    users: '2000',
    product_name: 'KPR Plus BNI',
    product_type: 'Kredit kepemilikan Pejabat',
    year_fix_rate: '4.2',
    max_tenor: '30',
    loan_to_value: '80',
    guarantee: 'Rumah, Apartemen',
    target_market: 'Pengusaha, Profesional',
    commision: '1.5',
    penalty_fee: '1',
    interest_rate: '4.2',
    fix_rate: '4.3',
    description:
      'KPR Plus BNI menawarkan kemudahan untuk membeli rumah impian dengan bunga yang lebih ringan.',
    appraisal: '1.8',
    floating: '2.0',
    url: 'null',
  },
  {
    id: 15,
    img: 'https://www.danamon.co.id/-/media/ICON-DCWCOID/LOGO-HEADER/v2/logo-danamon-new.jpg?h=65&iar=0&mh=65&w=260&hash=7956F6C1540D0E791F9382A68CF12C90',
    bank_name: 'Danamon',
    rating: '3',
    reviews: '45',
    users: '600',
    product_name: 'KPR Danamon Syariah',
    product_type: 'Kredit kepemilikan Rakyat',
    year_fix_rate: '5.0',
    max_tenor: '20',
    loan_to_value: '85',
    guarantee: 'Rumah, Apartemen',
    target_market: 'Karyawan, Pengusaha',
    commision: '1.3',
    penalty_fee: '0',
    interest_rate: '5.1',
    fix_rate: '5.0',
    description:
      'KPR Syariah Danamon menawarkan solusi pembiayaan rumah sesuai prinsip syariah.',
    appraisal: '1.7',
    floating: '1.9',
    url: 'null',
  },
];
